version = 1

test_patterns = ["app/javascript/mastodon/**/__tests__/**"]

exclude_patterns = [
  "db/migrate/**",
  "db/post_migrate/**"
]

[[analyzers]]
name = "ruby"

  [analyzers.meta]
  cyclomatic_complexity_threshold = "low"
