version = 1

test_patterns = ["app/javascript/mastodon/**/__tests__/**"]

exclude_patterns = [
  "db/migrate/**",
  "db/post_migrate/**"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ruby"

  [analyzers.meta]
  cyclomatic_complexity_threshold = "high"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "jest",
    "nodejs"
  ]
